/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TeacherCurriculumRouteImport } from './routes/teacher.curriculum'
import { Route as TeacherClassClassIdRouteImport } from './routes/teacher.class.$classId'
import { Route as TeacherClassClassIdStudentStudentIdRouteImport } from './routes/teacher.class.$classId.student.$studentId'
import { Route as IndexRouteImport } from './routes/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherCurriculumRoute = TeacherCurriculumRouteImport.update({
  id: '/teacher/curriculum',
  path: '/teacher/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassClassIdRoute = TeacherClassClassIdRouteImport.update({
  id: '/teacher/class/$classId',
  path: '/teacher/class/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassClassIdStudentStudentIdRoute =
  TeacherClassClassIdStudentStudentIdRouteImport.update({
    id: '/teacher/class/$classId/student/$studentId',
    path: '/teacher/class/$classId/student/$studentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/platform': typeof PlatformRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/teacher': typeof TeacherRoute
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRoute
  '/teacher/class/$classId/student/$studentId': typeof TeacherClassClassIdStudentStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/platform': typeof PlatformRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/teacher': typeof TeacherRoute
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRoute
  '/teacher/class/$classId/student/$studentId': typeof TeacherClassClassIdStudentStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/platform': typeof PlatformRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/teacher': typeof TeacherRoute
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/teacher/class/$classId': typeof TeacherClassClassIdRoute
  '/teacher/class/$classId/student/$studentId': typeof TeacherClassClassIdStudentStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/platform' | '/chat' | '/login' | '/teacher' | '/teacher/curriculum' | '/teacher/class/$classId' | '/teacher/class/$classId/student/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/platform' | '/chat' | '/login' | '/teacher' | '/teacher/curriculum' | '/teacher/class/$classId' | '/teacher/class/$classId/student/$studentId'
  id: '__root__' | '/' | '/admin' | '/platform' | '/chat' | '/login' | '/teacher' | '/teacher/curriculum' | '/teacher/class/$classId' | '/teacher/class/$classId/student/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PlatformRoute: typeof PlatformRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  TeacherRoute: typeof TeacherRoute
  TeacherCurriculumRoute: typeof TeacherCurriculumRoute
  TeacherClassClassIdRoute: typeof TeacherClassClassIdRoute
  TeacherClassClassIdStudentStudentIdRoute: typeof TeacherClassClassIdStudentStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/curriculum': {
      id: '/teacher/curriculum'
      path: '/teacher/curriculum'
      fullPath: '/teacher/curriculum'
      preLoaderRoute: typeof TeacherCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/class/$classId': {
      id: '/teacher/class/$classId'
      path: '/teacher/class/$classId'
      fullPath: '/teacher/class/$classId'
      preLoaderRoute: typeof TeacherClassClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/class/$classId/student/$studentId': {
      id: '/teacher/class/$classId/student/$studentId'
      path: '/teacher/class/$classId/student/$studentId'
      fullPath: '/teacher/class/$classId/student/$studentId'
      preLoaderRoute: typeof TeacherClassClassIdStudentStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PlatformRoute: PlatformRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  TeacherRoute: TeacherRoute,
  TeacherCurriculumRoute: TeacherCurriculumRoute,
  TeacherClassClassIdRoute: TeacherClassClassIdRoute,
  TeacherClassClassIdStudentStudentIdRoute: TeacherClassClassIdStudentStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
